apiVersion: batch/v1
kind: Job
metadata:
  generateName: argocd-newman-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: argocd-newman
        image: busybox
        args:
          - wget
          - --spider
          - el-job-listener.default.svc.cluster.local:8080
      restartPolicy: Never
